apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "engress-edge.fullname" . }}-config
  labels:
    {{- include "engress-edge.labels" . | nindent 4 }}
data:
  edge.yaml: |
    http_addr: ":80"
    https_addr: ":443"
    tunnel_addr: ":4433"
    domain_suffix: {{ .Values.config.domainSuffix | quote }}
    base_domain: {{ .Values.config.baseDomain | quote }}
    control_api_url: {{ .Values.config.controlApiUrl | quote }}
    cert_cache_dir: "/data/certs"
    mtls_mode: {{ .Values.config.mtlsMode | quote }}
    db:
      driver: sqlite
      dsn: "/data/engress.db"
    acme:
      directory: "https://acme-v02.api.letsencrypt.org/directory"
      email: "ops@engress.io"
