replicaCount: 1

image:
  repository: 327796148992.dkr.ecr.us-east-2.amazonaws.com/engress-staging-edge
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  name: engress-edge
  annotations: {}

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 384Mi

autoscaling:
  enabled: false

service:
  nlb:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP
      - name: https
        port: 443
        targetPort: 443
        protocol: TCP
      - name: tunnel
        port: 4433
        targetPort: 4433
        protocol: TCP
      - name: tcp-mux
        port: 4444
        targetPort: 4444
        protocol: TCP
      - name: udp-mux
        port: 4445
        targetPort: 4445
        protocol: UDP

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
  hosts:
    - host: edge-origin-east.staging.engress.io
      paths:
        - path: /
          pathType: Prefix

config:
  baseDomain: staging.engress.io
  domainSuffix: .edge.staging.engress.io
  controlApiUrl: http://engress-core:8080
  metricsApiUrl: http://engress-core:8080
  controlOriginHost: edge-origin-east.staging.engress.io
  mtlsMode: required
  awsRegion: us-east-2
  acmeProduction: false
  logLevel: debug
  environment: staging

edgeSecrets: engress-edge-secrets-staging

pdb:
  minAvailable: 0
